//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_Web_Equipo10A {
    
    public partial class Default {
        
        /// <summary>
        /// Control txtBusqueda.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;
        
        /// <summary>
        /// Control btnBuscar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        
        /// <summary>
        /// Control pnlResultados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultados;
        
        /// <summary>
        /// Control litResumen.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litResumen;
        
        /// <summary>
        /// Control rptResultados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultados;
    }
}


