CREATE DATABASE E_COMMERCE_DB
COLLATE Latin1_General_CI_AI

USE E_COMMERCE_DB
GO

CREATE TABLE USUARIOS(
IDUsuario INTEGER PRIMARY KEY IDENTITY(1,1),
Email NVARCHAR(200) NOT NULL UNIQUE,
Password NVARCHAR(20) NOT NULL ,
DNI VARCHAR (15) NOT NULL,
Nombre VARCHAR (50) NOT NULL,
Apellido VARCHAR (50) NOT NULL,
Telefono VARCHAR (20) NULL,
Domicilio VARCHAR (100) NULL,
TipoUsuario BIT NOT NULL
)

CREATE TABLE CATEGORIAS(
IDCategoria INTEGER PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR (50) NOT NULL UNIQUE
)

CREATE TABLE ESTADOSARTICULO(
IDEstado INTEGER PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR (50) NOT NULL UNIQUE
)

CREATE TABLE ARTICULOS(
IDArticulo INTEGER PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR (50) NOT NULL,
Descripcion VARCHAR (1000) NULL,
Precio MONEY NOT NULL,
IDCategoria INTEGER NOT NULL,
IDEstado INTEGER NOT NULL,
FOREIGN KEY (IDCategoria) REFERENCES CATEGORIAS(IDCategoria),
FOREIGN KEY (IDEstado) REFERENCES ESTADOSARTICULO(IDEstado)
)

CREATE TABLE IMAGENESARTICULO(
IDImagen INTEGER PRIMARY KEY IDENTITY(1,1),
IDArticulo INTEGER NOT NULL,
RutaImagen VARCHAR (500) NULL,
FOREIGN KEY (IDArticulo) REFERENCES ARTICULOS (IDArticulo)
)

CREATE TABLE RESERVAS(
IDReserva INTEGER PRIMARY KEY IDENTITY(1,1),
IDUsuario INTEGER NOT NULL,
FechaReserva DATETIME NOT NULL,
FechaVencimientoReserva DATETIME NOT NULL,
MontoSeña MONEY NOT NULL,
EstadoReserva BIT NOT NULL
FOREIGN KEY (IDUsuario) REFERENCES USUARIOS (IDUsuario)
)

CREATE TABLE ARTICULOSXRESERVA(
IDReserva INTEGER NOT NULL,
IDArticulo INTEGER NOT NULL,
PRIMARY KEY (IDReserva,IDArticulo),
FOREIGN KEY (IDReserva) REFERENCES RESERVAS (IDReserva),
FOREIGN KEY (IDArticulo) REFERENCES ARTICULOS (IDArticulo)
)

CREATE TABLE VENTAS(
IDVenta INTEGER PRIMARY KEY IDENTITY(1,1),
IDReserva INTEGER NOT NULL,
FechaVenta DATETIME NOT NULL,
PrecioFinal MONEY NOT NULL
FOREIGN KEY (IDReserva) REFERENCES RESERVAS (IDReserva)
)

INSERT INTO CATEGORIAS(Nombre)
VALUES 
    ('Sin Categoria'),
    ('Mueble'),
    ('Electrodomestico'),
    ('Bazar');

INSERT INTO ESTADOSARTICULO(Nombre)
VALUES 
    ('Disponible'),
    ('Reservado'),
    ('Vendido');

INSERT INTO ARTICULOS(Nombre, Descripcion, Precio, IDCategoria, IDEstado)
VALUES
    ('Heladera', 'Heladera Gafa con Frizzer', 100000, 3, 1),
    ('Mesa Ratona', 'Mesa ratona en excelente estado de 60X100 cm', 50000, 2, 1),
    ('Set Posillos', 'Set de 4 Posillos con platito, poco uso', 10000, 4, 2)

INSERT INTO IMAGENESARTICULO (IDArticulo, RutaImagen)
VALUES 
(1, 'Content/Uploads/Articulos/HeladeraGafaFreezer01.webp'),
(2, 'Content/Uploads/Articulos/MesaRatona01.webp'),
(3, 'Content/Uploads/Articulos/SetPosillos01.jpg');
