use E_COMMERCE_DB
go

---MODIFICACION TABLA USUARIOS
ALTER TABLE USUARIOS
ALTER COLUMN TipoUsuario TINYINT NOT NULL

ALTER TABLE USUARIOS
ADD CONSTRAINT DF_USUARIOS_TipoUsuario DEFAULT 0 FOR TipoUsuario

ALTER TABLE USUARIOS
ADD IDAdministrador INT NULL

ALTER TABLE USUARIOS
ADD FechaAlta DATETIME NULL

ALTER TABLE USUARIOS
ADD FechaVencimiento DATETIME NULL

ALTER TABLE USUARIOS
ADD Activo BIT NOT NULL DEFAULT 1

---MODIFICACION TABLA ARTICULOS
ALTER TABLE ARTICULOS	
ADD IDAdministrador INT NOT NULL DEFAULT 1

---MODIFICACION TABLA CATEGORIAS
ALTER TABLE CATEGORIAS	
ADD IDAdministrador INT NOT NULL DEFAULT 1

---MODIFICACION TABLA RESERVAS
ALTER TABLE RESERVAS	
ADD IDAdministrador INT NOT NULL DEFAULT 1

---MODIFICACION TABLA VENTAS
ALTER TABLE VENTAS	
ADD IDAdministrador INT NOT NULL DEFAULT 1

---CREACION TABLA FAVORITOS
CREATE TABLE FAVORITOS(
    IDFavorito INT PRIMARY KEY IDENTITY(1,1),
    IDUsuario INT NOT NULL,
    IDArticulo INT NOT NULL,
    IDAdministrador INT NOT NULL,
    FechaAgregado DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (IDUsuario) REFERENCES USUARIOS(IDUsuario),
    FOREIGN KEY (IDArticulo) REFERENCES ARTICULOS(IDArticulo),
    UNIQUE (IDUsuario, IDArticulo)
)

---CREACION TABLA CARRITOS
CREATE TABLE CARRITOS(
    IDCarrito INT PRIMARY KEY IDENTITY(1,1),
    IDUsuario INT NOT NULL UNIQUE,
    IDAdministrador INTEGER NOT NULL,
    FechaUltimaActualizacion DATETIME NOT NULL DEFAULT GETDATE(),
	Activo BIT NOT NULL DEFAULT 1,
    FOREIGN KEY (IDUsuario) REFERENCES USUARIOS(IDUsuario)
)

---CREACION TABLA ARTICULOSXCARRITO
CREATE TABLE ARTICULOSXCARRITO(
    IDCarrito INTEGER NOT NULL,
    IDArticulo INTEGER NOT NULL,
    FechaAgregado DATETIME NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (IDCarrito, IDArticulo),
    FOREIGN KEY (IDCarrito) REFERENCES CARRITOS(IDCarrito),
    FOREIGN KEY (IDArticulo) REFERENCES ARTICULOS(IDArticulo)
)